stages:
  - build
  - test

build_local:
  type: build
  tags:
    - linux
  script:
    # Do not build zmq if it is already installed by the system to speed up run
    # We depend on zmq version 4.
    - "mkdir build && cd build && grep 'ZMQ_VERSION_MAJOR 4' /usr/include/zmq.h &>/dev/null && cmake .. || cmake -DINSTALL_ZMQ=ON .. && make install"
  artifacts:
    paths:
      - build/
      - install/

test_local:
  type: test
  tags:
    - linux
  script:
    - "cd build && source ../install/bin/melissa_set_env.sh && env && ctest --verbose"
  dependencies:
    - build_local


