stages:
  - build
  - test

build_local:
  type: build
  tags:
    - linux
  script:
    - "mkdir build && cd build && cmake .. && make install"
  artifacts:
    paths:
      - build/
      - install/

test_local:
  type: test
  tags:
    - linux
  script:
    - "cd build && source ../install/bin/melissa_set_env.sh && env && ctest --verbose"
  dependencies:
    - build_local


